trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: SyncBranches
    displayName: "Sync Branches from Azure DevOps to GitHub"
    jobs:
      - job: SyncJob
        displayName: "Sync Job"
        steps:
          # Fazer o checkout do repositório
          - checkout: self
            persistCredentials: false
            fetchDepth: 0
            displayName: "Checkout do Repositório"

          # Adicionar o GitHub como remote
          - script: |
              git fetch
            displayName: "Adicionar Remote do GitHub"

          # Sincronizar com o GitHub
          - script: |
              git config --global user.email "projetil.tech@outlook.com"
              git config --global user.name "Projetil Devops"
              git add .
              git commit -m "teste"
              git push $(Build.SourceBranchName)
            displayName: "Sincronizar com o GitHub"