# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  Repository: projetil/alpinistas-producao-customer-frontend
steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerhub'
      repository: '$(Repository)'
      command: 'buildAndPush'
      Dockerfile: './Dockerfile'
      tags: 'Prod$(Build.BuildNumber),latest'
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'alpinistasazure'
      appType: 'webAppContainer'
      WebAppName: 'alpinistas-producao-customer-frontend'
      DockerNamespace: 'index.docker.io'
      DockerRepository: '$(Repository)'
      DockerImageTag: 'Prod$(Build.BuildNumber)'