trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git config --global user.name "Azure DevOps"
    git config --global user.email "projetil.tech@outlook.com"
    echo "https://$(GITHUB_TOKEN)@github.com" > ~/.git-credentials
    git config --global credential.helper store
    git clone --branch main https://$(GITHUB_TOKEN)@github.com/Projetil/alpinistacustomer
    rsync -av --exclude='.git' . ./alpinistacustomer
    cd alpinistacustomer
    git pull
    ls
    git add .
    git commit -m "Sync from Azure DevOps"
    git push origin main --force
  displayName: 'Sync to GitHub'